// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UploadRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Script               string   `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_b57579493e902cf4, []int{0}
}
func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (dst *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(dst, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UploadRequest) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

type UploadResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_b57579493e902cf4, []int{1}
}
func (m *UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResponse.Unmarshal(m, b)
}
func (m *UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResponse.Marshal(b, m, deterministic)
}
func (dst *UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResponse.Merge(dst, src)
}
func (m *UploadResponse) XXX_Size() int {
	return xxx_messageInfo_UploadResponse.Size(m)
}
func (m *UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResponse proto.InternalMessageInfo

func (m *UploadResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UploadResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type RunRequest struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Env                  map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RunRequest) Reset()         { *m = RunRequest{} }
func (m *RunRequest) String() string { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()    {}
func (*RunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_b57579493e902cf4, []int{2}
}
func (m *RunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest.Unmarshal(m, b)
}
func (m *RunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest.Marshal(b, m, deterministic)
}
func (dst *RunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest.Merge(dst, src)
}
func (m *RunRequest) XXX_Size() int {
	return xxx_messageInfo_RunRequest.Size(m)
}
func (m *RunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest proto.InternalMessageInfo

func (m *RunRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RunRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RunRequest) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

type RunResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunResponse) Reset()         { *m = RunResponse{} }
func (m *RunResponse) String() string { return proto.CompactTextString(m) }
func (*RunResponse) ProtoMessage()    {}
func (*RunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_b57579493e902cf4, []int{3}
}
func (m *RunResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunResponse.Unmarshal(m, b)
}
func (m *RunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunResponse.Marshal(b, m, deterministic)
}
func (dst *RunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunResponse.Merge(dst, src)
}
func (m *RunResponse) XXX_Size() int {
	return xxx_messageInfo_RunResponse.Size(m)
}
func (m *RunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunResponse proto.InternalMessageInfo

func (m *RunResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_b57579493e902cf4, []int{4}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Size                 uint64               `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_b57579493e902cf4, []int{5}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ListResponse) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_b57579493e902cf4, []int{6}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_b57579493e902cf4, []int{7}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(dst, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UploadRequest)(nil), "api.UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "api.UploadResponse")
	proto.RegisterType((*RunRequest)(nil), "api.RunRequest")
	proto.RegisterMapType((map[string]string)(nil), "api.RunRequest.EnvEntry")
	proto.RegisterType((*RunResponse)(nil), "api.RunResponse")
	proto.RegisterType((*ListRequest)(nil), "api.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "api.ListResponse")
	proto.RegisterType((*DeleteRequest)(nil), "api.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "api.DeleteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// V8Client is the client API for V8 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type V8Client interface {
	Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error)
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (V8_ListClient, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type v8Client struct {
	cc *grpc.ClientConn
}

func NewV8Client(cc *grpc.ClientConn) V8Client {
	return &v8Client{cc}
}

func (c *v8Client) Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error) {
	out := new(UploadResponse)
	err := c.cc.Invoke(ctx, "/api.V8/Upload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v8Client) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, "/api.V8/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v8Client) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (V8_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_V8_serviceDesc.Streams[0], "/api.V8/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &v8ListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type V8_ListClient interface {
	Recv() (*ListResponse, error)
	grpc.ClientStream
}

type v8ListClient struct {
	grpc.ClientStream
}

func (x *v8ListClient) Recv() (*ListResponse, error) {
	m := new(ListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *v8Client) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/api.V8/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// V8Server is the server API for V8 service.
type V8Server interface {
	Upload(context.Context, *UploadRequest) (*UploadResponse, error)
	Run(context.Context, *RunRequest) (*RunResponse, error)
	List(*ListRequest, V8_ListServer) error
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterV8Server(s *grpc.Server, srv V8Server) {
	s.RegisterService(&_V8_serviceDesc, srv)
}

func _V8_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V8Server).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.V8/Upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V8Server).Upload(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V8_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V8Server).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.V8/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V8Server).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V8_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(V8Server).List(m, &v8ListServer{stream})
}

type V8_ListServer interface {
	Send(*ListResponse) error
	grpc.ServerStream
}

type v8ListServer struct {
	grpc.ServerStream
}

func (x *v8ListServer) Send(m *ListResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _V8_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V8Server).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.V8/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V8Server).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _V8_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.V8",
	HandlerType: (*V8Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _V8_Upload_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _V8_Run_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _V8_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _V8_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "core.proto",
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_core_b57579493e902cf4) }

var fileDescriptor_core_b57579493e902cf4 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x41, 0x6b, 0xdb, 0x30,
	0x14, 0xc7, 0x91, 0xed, 0x98, 0xe5, 0x79, 0xc9, 0x32, 0x6d, 0x04, 0xe3, 0xcb, 0x82, 0x60, 0x60,
	0x06, 0x73, 0xb6, 0x04, 0x46, 0xb6, 0x9d, 0x36, 0x96, 0xdb, 0x4e, 0x66, 0xdb, 0x61, 0x3d, 0x14,
	0x25, 0x56, 0x83, 0xa8, 0x63, 0xa9, 0xb6, 0x1c, 0x48, 0x6f, 0xfd, 0x0e, 0xfd, 0x46, 0xfd, 0x62,
	0xc5, 0x96, 0x44, 0xe2, 0xd0, 0x1e, 0x72, 0xd3, 0xfb, 0xfb, 0xbd, 0xbf, 0x7f, 0xef, 0x2f, 0x1b,
	0x60, 0x2d, 0x4a, 0x96, 0xc8, 0x52, 0x28, 0x81, 0x5d, 0x2a, 0x79, 0xf4, 0x6e, 0x23, 0xc4, 0x26,
	0x67, 0xd3, 0x56, 0x5a, 0xd5, 0x57, 0x53, 0xc5, 0xb7, 0xac, 0x52, 0x74, 0x2b, 0x75, 0x17, 0xf9,
	0x0e, 0x83, 0xbf, 0x32, 0x17, 0x34, 0x4b, 0xd9, 0x4d, 0xcd, 0x2a, 0x85, 0x31, 0x78, 0x05, 0xdd,
	0xb2, 0x10, 0x4d, 0x50, 0xdc, 0x4f, 0xdb, 0x33, 0x1e, 0x83, 0x5f, 0xad, 0x4b, 0x2e, 0x55, 0xe8,
	0xb4, 0xaa, 0xa9, 0xc8, 0x05, 0x0c, 0xed, 0x70, 0x25, 0x45, 0x51, 0x31, 0x3c, 0x04, 0x87, 0x67,
	0x66, 0xd6, 0xe1, 0x19, 0xfe, 0x0a, 0xb0, 0x2e, 0x19, 0x55, 0x2c, 0xbb, 0xa4, 0x7a, 0x3a, 0x98,
	0x45, 0x89, 0x86, 0x4a, 0x2c, 0x54, 0xf2, 0xc7, 0x42, 0xa5, 0x7d, 0xd3, 0xfd, 0x43, 0x91, 0x7b,
	0x04, 0x90, 0xd6, 0x85, 0xe5, 0x3a, 0x75, 0xb6, 0x9c, 0xce, 0x11, 0xe7, 0x07, 0x70, 0x59, 0xb1,
	0x0b, 0xdd, 0x89, 0x1b, 0x07, 0xb3, 0x30, 0xa1, 0x92, 0x27, 0x07, 0x87, 0x64, 0x59, 0xec, 0x96,
	0x85, 0x2a, 0xf7, 0x69, 0xd3, 0x14, 0x7d, 0x81, 0x17, 0x56, 0xc0, 0x23, 0x70, 0xaf, 0xd9, 0xde,
	0x98, 0x37, 0x47, 0xfc, 0x16, 0x7a, 0x3b, 0x9a, 0xd7, 0xd6, 0x5e, 0x17, 0xdf, 0x9c, 0x05, 0x22,
	0xef, 0x21, 0x68, 0x3d, 0xcd, 0xc2, 0x63, 0xf0, 0x45, 0xad, 0x64, 0xad, 0xcc, 0xb4, 0xa9, 0xc8,
	0x00, 0x82, 0xdf, 0xbc, 0x52, 0xe6, 0xdd, 0xe4, 0x0e, 0xc1, 0x4b, 0x5d, 0x3f, 0x13, 0xd4, 0x53,
	0xeb, 0x74, 0xc3, 0x73, 0xcf, 0x08, 0xaf, 0xb1, 0xab, 0xf8, 0x2d, 0x0b, 0xbd, 0x09, 0x8a, 0xbd,
	0xb4, 0x3d, 0x93, 0x39, 0x0c, 0x7e, 0xb1, 0x9c, 0x29, 0x76, 0x46, 0xa4, 0x64, 0x04, 0x43, 0x3b,
	0xa4, 0xc9, 0x67, 0x0f, 0x08, 0x9c, 0x7f, 0x0b, 0xfc, 0x19, 0x7c, 0x7d, 0xf7, 0x18, 0xb7, 0x41,
	0x77, 0xbe, 0xa2, 0xe8, 0x4d, 0x47, 0x33, 0x3b, 0xc7, 0xe0, 0xa6, 0x75, 0x81, 0x5f, 0x9d, 0x5c,
	0x4c, 0x34, 0x3a, 0x08, 0xa6, 0xf3, 0x23, 0x78, 0x4d, 0x5a, 0x58, 0x3f, 0x39, 0x0a, 0x32, 0x7a,
	0x7d, 0xa4, 0xe8, 0xe6, 0x4f, 0xa8, 0x61, 0xd1, 0x90, 0x86, 0xa5, 0xb3, 0xa6, 0x61, 0xe9, 0x6e,
	0xf1, 0xb3, 0xf7, 0xbf, 0xf9, 0x3f, 0x56, 0x7e, 0x1b, 0xe3, 0xfc, 0x31, 0x00, 0x00, 0xff, 0xff,
	0x35, 0x08, 0x34, 0x23, 0x39, 0x03, 0x00, 0x00,
}
